export enum ActionTypes {
  FETCH_PRODUCT = 'FETCH_PRODUCT',
  ADD_WISHLIST = 'ADD_WISHLIST',

  ADD_CART = 'ADD_CART',
  REMOVE_CART = 'REMOVE_CART',
  UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY',

  GET_USER_BY_TOKEN = 'GET_USER_BY_TOKEN',
  SET_PROFILE_LOADING = 'SET_PROFILE_LOADING',

  ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD',
}